apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-planets-api
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-planets-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flask-planets-api
    spec:
      containers:
        - image: gcr.io/learning-project-284206/github.com/grinit10/docker-flask-api
          imagePullPolicy: Always
          name: flask-planets-api
          ports:
            - containerPort: 5000
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: flask-planets-api-service
  namespace: default
spec:
  clusterIP: 10.11.246.223
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 31455
      port: 6001
      protocol: TCP
      targetPort: 5000
  selector:
    app: flask-planets-api
  sessionAffinity: None
  type: LoadBalancer
