apiVersion: v1
kind: Service
metadata:
  name: flask-planets-api-service
spec:
  selector:
    app: flask-planets-api
  ports:
  - protocol: "TCP"
    port: 6001
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-planets-api
spec:
  selector:
    matchLabels:
      app: flask-planets-api
  replicas: 2
  template:
    metadata:
      labels:
        app: flask-planets-api
    spec:
      containers:
      - name: flask-planets-api
        image: gcr.io/learning-project-284206/flask-planets-api:latest
#        image: flask-planets-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000